services:
  - type: web
    name: whatsapp-bot
    runtime: docker
    env: node
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
